In [1]:
import numpy as np
print("numpy import successfully ")


numpy import successfully 


In [2]:
# creating numpy array
arr1 = np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))


[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [3]:
list = [1,2,3,4]
print(list)
print(type(list))

[1, 2, 3, 4]
<class 'list'>


In [4]:
arr = np.arange(1,25)  ##arange means range of the function
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [5]:
##  2D array 
arr = np.zeros([3,4])  
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
## 3D array
## is there we use 2 blocks, 3 rows and 4 columns

arr = np.array([[[1,2,3,4],[8,4,5,6],[1,2,3,4]],[[9,7,8,9],[0,1,5,6],[1,6,7,8]]])
arr

array([[[1, 2, 3, 4],
        [8, 4, 5, 6],
        [1, 2, 3, 4]],

       [[9, 7, 8, 9],
        [0, 1, 5, 6],
        [1, 6, 7, 8]]])

In [7]:
arr = np.zeros((2,3,4))
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [8]:
arr = np.ones((2,3,4))
arr

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [9]:
arr = np.linspace(1,10,5)   ## linespace means take 5 values btw 1 to 10
arr


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [10]:
arr = np.linspace(1,10,5).reshape(5,1)    ## reshape means there 5 rows and 1 column and change size and convert into 2d array

In [11]:
arr = np.arange(0,30).reshape(6,5)   ## reshape value we define by our requirement(6*5=30)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [12]:
arr = np.arange(0,50).reshape(2,5,5)    ### 3D array 
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [13]:
# Random Initialization

# arr = np.random.randint(1,20,3) # 3 element
# arr

# arr = np.random.randint(1,10,(3,3)) # 2D array with 9 element
# arr

arr = np.random.randint(1,10,(3,3,3))  #3D array with 27 element
arr

array([[[5, 6, 7],
        [7, 9, 6],
        [1, 4, 3]],

       [[5, 4, 7],
        [3, 9, 1],
        [2, 1, 2]],

       [[2, 8, 4],
        [8, 6, 8],
        [4, 5, 3]]])

In [14]:
# arr = np.random.random(10)   ## take 10 value randomly btw o to 1
# arr

arr = np.random.randint(10)   ### take a value randomly btw 1 to 10
arr


6

In [15]:
arr = np.arange(0,30).reshape(6,5)  
arr


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [16]:
arr.dtype


dtype('int32')

In [17]:
arr.ndim


2

In [18]:
arr.shape

(6, 5)

In [19]:
arr.size

30

In [20]:
arr.ravel   ##used to convert a multi-dimensional array into a one-dimensional array

<function ndarray.ravel>

In [21]:
lst = [[1,2,3],[4,5,6]]
arr = np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr.shape

(2, 3)

In [ ]:
arr.T   ## T means transpose the shape(row to column and column to row)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [24]:
arr.T.shape

(3, 2)